### ISSUE TITLE
Build trouble with 0.2.0 on apple silicon

### ISSUE THREAD

**Issue by neongrau** [miyucy/snappy#43]
Was getting errors even after `brew install snappy`.

Finally was able to build via
`gem install snappy -- --with-cxxflags=\"-std=c++17\"`

Side info: With rvm you should use ruby >2.7.x as older ruby versions have some issues with osx arm64. Some web suggested workarounds just give you [broken] state on rvm list.
The macOS Monterey shipped ruby 2.6.8 was likely manually fixed by apple.

**Comment by miyucy** [comment]
Solved via https://github.com/miyucy/snappy/pull/42 ?

**Comment by neongrau** [comment]
Yes seems to be solved. i was able to update to 0.3.0 via bundler.
Thanks a lot!

**Comment by miyucy** [comment]
Thanks for confirms!

**Comment by nitin302** [comment]
anyone was able to fix this for ruby > 2.7?
